// Generated from libavcodec/vulkan/dwt.comp
const char *ff_source_dwt_comp =
"#extension GL_EXT_scalar_block_layout : require\n"
"\n"
"layout(local_size_x = 8, local_size_y = 8, local_size_z = 3) in;\n"
"\n"
"layout(std430, buffer_reference, buffer_reference_align = 4) buffer DwtCoef {\n"
"    uint coef_buf[];\n"
"};\n"
"\n"
"layout(push_constant, scalar) uniform ComputeInfo {\n"
"    int wavelet_depth;\n"
"    int s;\n"
"    DwtCoef p[3];\n"
"};\n"
"\n"
"void main() {\n"
"    #pragma unroll\n"
"    int stride = imageSize(planes[0]).x;\n"
"    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
"    for (int l = 0; l < wavelet_depth - 1; l++) {\n"
"        const uint plane_idx = gl_LocalInvocationID.z;\n"
"        /* dst_size is twice the level subband size and represents our work area */\n"
"        ivec2 dst_size = imageSize(planes[plane_idx]) >> l;\n"
"        ivec2 synth_size = dst_size >> 1;\n"
"        if (any(greaterThan(coord, dst_size))) {\n"
"            break;\n"
"        }\n"
"\n"
"        /* For horizontal synth pass, each invocation handles a horizontal pair of pixels */\n"
"        ivec2 coord_x = coord << ivec2(1, 0);\n"
"        if (all(lessThan(coord_x, synth_size))) {\n"
"            uint a = uint(imageLoad(planes[plane_idx], coord_x).x * 255.0);\n"
"            uint b = uint(imageLoad(planes[plane_idx], coord_x + ivec2(1, 0)).x * 255.0);\n"
"            uint dst_b = (b - a) * (1 << s);\n"
"            uint dst_a = a * (1 << s) + ((dst_b + 1) >> 1);\n"
"            p[plane_idx].coef_buf[coord_x.y * stride + coord_x.x] = dst_a;\n"
"            p[plane_idx].coef_buf[coord_x.y * stride + coord_x.x + 1] = dst_b;\n"
"        }\n"
"        memoryBarrier();\n"
"\n"
"        /* For vertical synth pass, each invocation handles a vertical pair of pixels */\n"
"        ivec2 coord_y = coord << ivec2(0, 1);\n"
"        if (all(lessThan(coord_y, synth_size))) {\n"
"            uint a = uint(imageLoad(planes[plane_idx], coord_y).x * 255.0);\n"
"            uint b = uint(imageLoad(planes[plane_idx], coord_y + ivec2(0, 1)).x * 255.0);\n"
"            uint dst_b = b - a;\n"
"            uint dst_a = a + ((dst_b + 1) >> 1);\n"
"            p[plane_idx].coef_buf[coord_y.y * stride + coord_y.x] = dst_a;\n"
"            p[plane_idx].coef_buf[(coord_y.y + 1) * stride + coord_y.x + 1] = dst_b;\n"
"        }\n"
"        memoryBarrier();\n"
"\n"
"        /* Finally deinterleave result. Here each invocation is responsible for a single pixel */\n"
"        ivec2 subband = coord & int(1);\n"
"        ivec2 new_coord = subband * synth_size + (coord >> 1);\n"
"        uint texel = p[plane_idx].coef_buf[coord.y * stride + coord.x];\n"
"        barrier();\n"
"        p[plane_idx].coef_buf[new_coord.y * stride + new_coord.x] = texel;\n"
"    }\n"
"}\n"
;
