// Generated from libavcodec/vulkan/dwt_hor.comp
const char *ff_source_dwt_hor_comp =
"#extension GL_EXT_scalar_block_layout : require\n"
"#extension GL_EXT_debug_printf : require\n"
"\n"
"layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;\n"
"\n"
"layout(scalar, buffer_reference, buffer_reference_align = 4) buffer DwtCoef {\n"
"    int coef_buf[];\n"
"};\n"
"\n"
"struct Plane {\n"
"    ivec2 dim;\n"
"    int coef_stride;\n"
"    int pad;\n"
"};\n"
"\n"
"#define VC2_TRANSFORM_HAAR (3)\n"
"#define VC2_TRANSFORM_HAAR_S (4)\n"
"#define VC2_TRANSFORM_5_3 (1)\n"
"\n"
"layout(push_constant, scalar) uniform ComputeInfo {\n"
"    int s;\n"
"    int diff_offset;\n"
"    int level;\n"
"    int wavelet_type;\n"
"    Plane planes[3];\n"
"    DwtCoef dst_buf[3];\n"
"    DwtCoef src_buf[3];\n"
"};\n"
"\n"
"void main() {\n"
"    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
"\n"
"    /* For horizontal synth pass, each invocation handles a horizontal pair of pixels */\n"
"    uint plane_idx = gl_GlobalInvocationID.z;\n"
"    ivec2 coord_x = coord << ivec2(1, 0);\n"
"    ivec2 work_area = planes[plane_idx].dim >> level;\n"
"    ivec2 dwt_area = work_area >> 1;\n"
"    if (wavelet_type == VC2_TRANSFORM_HAAR || wavelet_type == VC2_TRANSFORM_HAAR_S) {\n"
"        if (any(greaterThanEqual(coord_x, work_area))) {\n"
"            return;\n"
"        }\n"
"        int start = planes[plane_idx].coef_stride * coord_x.y;\n"
"        int a = src_buf[plane_idx].coef_buf[start + coord_x.x];\n"
"        int b = src_buf[plane_idx].coef_buf[start + coord_x.x + 1];\n"
"        int dst_b = (b - a) * (1 << s);\n"
"        int dst_a = a * (1 << s) + ((dst_b + 1) >> 1);\n"
"        dst_buf[plane_idx].coef_buf[start + coord_x.x] = dst_a;\n"
"        dst_buf[plane_idx].coef_buf[start + coord_x.x + 1] = dst_b;\n"
"    } else {\n"
"        // Shift in one bit that is used for additional precision\n"
"        int start = planes[plane_idx].coef_stride * coord.y;\n"
"        dst_buf[plane_idx].coef_buf[start + coord.x] = src_buf[plane_idx].coef_buf[start + coord.x] << 1;\n"
"        if (any(greaterThanEqual(coord, dwt_area))) {\n"
"            return;\n"
"        }\n"
"        // Lifting stage 2\n"
"        if (coord.x < dwt_area.x - 1) {\n"
"            int a = dst_buf[plane_idx].coef_buf[start + 2 * coord.x + 1];\n"
"            int b = dst_buf[plane_idx].coef_buf[start + 2 * coord.x];\n"
"            int c = dst_buf[plane_idx].coef_buf[start + 2 * (coord.x + 1)];\n"
"            a -= (b + c + 1) >> 1;\n"
"            dst_buf[plane_idx].coef_buf[start + 2 * coord.x + 1] = a;\n"
"        } else {\n"
"            int a = dst_buf[plane_idx].coef_buf[start + work_area.x - 1];\n"
"            int b = dst_buf[plane_idx].coef_buf[start + work_area.x - 2];\n"
"            a -= (2 * b + 1) >> 1;\n"
"            dst_buf[plane_idx].coef_buf[start + work_area.x - 1] = a;\n"
"        }\n"
"\n"
"        // Lifting stage 1\n"
"        if (coord.x == 0) {\n"
"            dst_buf[plane_idx].coef_buf[start] += (2 * dst_buf[plane_idx].coef_buf[start + 1] + 2) >> 2;\n"
"        } else if (coord.x < dwt_area.x - 1) {\n"
"            int a = dst_buf[plane_idx].coef_buf[start + 2 * coord.x];\n"
"            int b = dst_buf[plane_idx].coef_buf[start + 2 * coord.x - 1];\n"
"            int c = dst_buf[plane_idx].coef_buf[start + 2 * coord.x + 1];\n"
"            a += (b + c + 2) >> 2;\n"
"            dst_buf[plane_idx].coef_buf[start + 2 * coord.x] = a;\n"
"        } else {\n"
"            int a = dst_buf[plane_idx].coef_buf[start + work_area.x - 2];\n"
"            int b = dst_buf[plane_idx].coef_buf[start + work_area.x - 1];\n"
"            int c = dst_buf[plane_idx].coef_buf[start + work_area.x - 3];\n"
"            a += (c + b + 2) >> 2;\n"
"            dst_buf[plane_idx].coef_buf[start + work_area.x - 2] = a;\n"
"        }\n"
"    }\n"
"}\n"
;
