// Generated from libavcodec/vulkan/dwt_ver.comp
const char *ff_source_dwt_ver_comp =
"#extension GL_EXT_scalar_block_layout : require\n"
"#extension GL_EXT_debug_printf : require\n"
"\n"
"layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;\n"
"\n"
"layout(scalar, buffer_reference, buffer_reference_align = 4) buffer DwtCoef {\n"
"    int coef_buf[];\n"
"};\n"
"\n"
"layout(push_constant, scalar) uniform ComputeInfo {\n"
"    int wavelet_depth;\n"
"    int s;\n"
"    int stride;\n"
"    int diff_offset;\n"
"    ivec2 work_area;\n"
"    DwtCoef dst_buf[3];\n"
"    DwtCoef src_buf[3];\n"
"};\n"
"\n"
"void main() {\n"
"    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
"\n"
"    /* For vertical synth pass, each invocation handles a vertical pair of pixels */\n"
"    uint plane_idx = gl_GlobalInvocationID.z;\n"
"    ivec2 coord_y = coord << ivec2(0, 1);\n"
"    if (any(greaterThanEqual(coord_y, work_area))) {\n"
"        return;\n"
"    }\n"
"\n"
"    int a = dst_buf[plane_idx].coef_buf[coord_y.y * stride + coord_y.x];\n"
"    int b = dst_buf[plane_idx].coef_buf[(coord_y.y + 1) * stride + coord_y.x];\n"
"    int dst_b = b - a;\n"
"    int dst_a = a + ((dst_b + 1) >> 1);\n"
"    dst_buf[plane_idx].coef_buf[coord_y.y * stride + coord_y.x] = dst_a;\n"
"    dst_buf[plane_idx].coef_buf[(coord_y.y + 1) * stride + coord_y.x] = dst_b;\n"
"}\n"
;
