// Generated from libavcodec/vulkan/dwt_upload.comp
const char *ff_source_dwt_upload_comp =
"#extension GL_EXT_scalar_block_layout : require\n"
"#extension GL_EXT_debug_printf : require\n"
"#extension GL_EXT_shader_explicit_arithmetic_types : require\n"
"\n"
"layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;\n"
"\n"
"layout(scalar, buffer_reference, buffer_reference_align = 4) buffer DwtCoef {\n"
"    int coef_buf[];\n"
"};\n"
"\n"
"layout(scalar, buffer_reference, buffer_reference_align = 1) buffer PlaneBuf {\n"
"    uint8_t data[];\n"
"};\n"
"\n"
"layout(push_constant, scalar) uniform ComputeInfo {\n"
"    int wavelet_depth;\n"
"    int s;\n"
"    int stride;\n"
"    int diff_offset;\n"
"    ivec2 work_area;\n"
"    PlaneBuf src_buf[3];\n"
"    DwtCoef dst_buf[3];\n"
"};\n"
"\n"
"void main() {\n"
"    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
"    uint plane_idx = gl_GlobalInvocationID.z;\n"
"    uint coef_idx = coord.y * stride + coord.x;\n"
"    const uint8_t texel = src_buf[plane_idx].data[coef_idx];\n"
"    dst_buf[plane_idx].coef_buf[coef_idx] = int(texel - diff_offset);\n"
"}\n"
;
