// Generated from libavcodec/vulkan/dwt_ver_legall.comp
const char *ff_source_dwt_ver_legall_comp =
"#extension GL_EXT_scalar_block_layout : require\n"
"#extension GL_EXT_debug_printf : require\n"
"#extension GL_EXT_buffer_reference : require\n"
"\n"
"layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;\n"
"\n"
"layout(scalar, buffer_reference, buffer_reference_align = 4) buffer DwtCoef {\n"
"    int coef_buf[];\n"
"};\n"
"\n"
"struct Plane {\n"
"    ivec2 dim;\n"
"    int coef_stride;\n"
"    int pad;\n"
"};\n"
"\n"
"layout(push_constant, scalar) uniform ComputeInfo {\n"
"    int s;\n"
"    int diff_offset;\n"
"    int level;\n"
"    int wavelet_type;\n"
"    Plane planes[3];\n"
"    DwtCoef dst_buf[3];\n"
"    DwtCoef src_buf[3];\n"
"};\n"
"\n"
"void main() {\n"
"    int coord_x = int(gl_GlobalInvocationID.x);\n"
"    uint plane_idx = gl_GlobalInvocationID.z;\n"
"    ivec2 work_area = planes[plane_idx].dim >> level;\n"
"    if (coord_x >= work_area.x) {\n"
"        return;\n"
"    }\n"
"\n"
"    DwtCoef dst = dst_buf[plane_idx];\n"
"    ivec2 dwt_area = work_area >> 1;\n"
"    int stride = planes[plane_idx].coef_stride;\n"
"\n"
"    // Lifting stage 2\n"
"    for (int y = 1; y < work_area.y - 2; y += 2) {\n"
"        dst.coef_buf[stride * y + coord_x] -= (dst.coef_buf[stride * (y - 1) + coord_x] +\n"
"                                               dst.coef_buf[stride * (y + 1) + coord_x] + 1) >> 1;\n"
"    }\n"
"    dst.coef_buf[stride * (work_area.y - 1) + coord_x] -= (2 * dst.coef_buf[stride * (work_area.y - 2) + coord_x] + 1) >> 1;\n"
"\n"
"    // Lifting stage 1\n"
"    dst.coef_buf[coord_x] += (2 * dst.coef_buf[stride + coord_x] + 2) >> 2;\n"
"    for (int y = 2; y < work_area.y - 2; y += 2) {\n"
"        dst.coef_buf[stride * y + coord_x] += (dst.coef_buf[stride * (y + 1) + coord_x] +\n"
"                                               dst.coef_buf[stride * (y - 1) + coord_x] + 2) >> 2;\n"
"    }\n"
"    dst.coef_buf[stride * (work_area.y - 2) + coord_x] += (dst.coef_buf[stride * (work_area.y - 3) + coord_x] +\n"
"                                                           dst.coef_buf[stride * (work_area.y - 1) + coord_x] + 2) >> 2;\n"
"}\n"
;
