// Generated from libavcodec/vulkan/dwt_hor_legall.comp
const char *ff_source_dwt_hor_legall_comp =
"#extension GL_EXT_scalar_block_layout : require\n"
"#extension GL_EXT_debug_printf : require\n"
"\n"
"layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;\n"
"\n"
"layout(scalar, buffer_reference, buffer_reference_align = 4) buffer DwtCoef {\n"
"    int coef_buf[];\n"
"};\n"
"\n"
"struct Plane {\n"
"    ivec2 dim;\n"
"    int coef_stride;\n"
"    int pad;\n"
"};\n"
"\n"
"#define VC2_TRANSFORM_HAAR (3)\n"
"#define VC2_TRANSFORM_HAAR_S (4)\n"
"#define VC2_TRANSFORM_5_3 (1)\n"
"\n"
"layout(push_constant, scalar) uniform ComputeInfo {\n"
"    int s;\n"
"    int diff_offset;\n"
"    int level;\n"
"    int wavelet_type;\n"
"    Plane planes[3];\n"
"    DwtCoef dst_buf[3];\n"
"    DwtCoef src_buf[3];\n"
"};\n"
"\n"
"void main() {\n"
"    int coord_y = int(gl_GlobalInvocationID.x);\n"
"    uint plane_idx = gl_GlobalInvocationID.z;\n"
"    ivec2 work_area = planes[plane_idx].dim >> level;\n"
"    if (coord_y >= work_area.y) {\n"
"        return;\n"
"    }\n"
"\n"
"    DwtCoef src = src_buf[plane_idx];\n"
"    DwtCoef dst = dst_buf[plane_idx];\n"
"    ivec2 dwt_area = work_area >> 1;\n"
"    int start = planes[plane_idx].coef_stride * coord_y;\n"
"    \n"
"    // Shift in one bit that is used for additional precision\n"
"    for (int x = 0; x < work_area.y; x++) {\n"
"        dst.coef_buf[start + x] = src.coef_buf[start + x] << 1;\n"
"    }\n"
"\n"
"    // Lifting stage 2\n"
"    for (int x = 0; x < dwt_area.x - 1; x++) {\n"
"        dst.coef_buf[start + 2 * x + 1] -= (dst.coef_buf[start + 2 * x] +\n"
"                                            dst.coef_buf[start + 2 * x + 2] + 1) >> 1;\n"
"    }\n"
"    dst.coef_buf[start + work_area.x - 1] -= (2 * dst.coef_buf[start + work_area.x - 2] + 1) >> 1;\n"
"\n"
"    // Lifting stage 1\n"
"    dst.coef_buf[start] += (2 * dst.coef_buf[start + 1] + 2) >> 2;\n"
"    for (int x = 1; x < dwt_area.x - 1; x++) {\n"
"        dst.coef_buf[start + 2 * x] += (dst.coef_buf[start + 2 * x - 1] +\n"
"                                        dst.coef_buf[start + 2 * x + 1] + 2) >> 2;\n"
"    }\n"
"    dst.coef_buf[start + work_area.x - 2] += (dst.coef_buf[start + work_area.x - 3] +\n"
"                                              dst.coef_buf[start + work_area.x - 1] + 2) >> 2;\n"
"}\n"
;
