// Generated from libavcodec/vulkan/dwt_upload.comp
const char *ff_source_dwt_upload_comp =
"#extension GL_EXT_scalar_block_layout : require\n"
"#extension GL_EXT_debug_printf : require\n"
"#extension GL_EXT_shader_explicit_arithmetic_types : require\n"
"\n"
"layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;\n"
"\n"
"layout(scalar, buffer_reference, buffer_reference_align = 4) buffer DwtCoef {\n"
"    int coef_buf[];\n"
"};\n"
"\n"
"layout(scalar, buffer_reference, buffer_reference_align = 1) buffer PlaneBuf {\n"
"    uint8_t data[];\n"
"};\n"
"\n"
"struct Plane {\n"
"    ivec2 dim;\n"
"    ivec2 dwt_dim;\n"
"    int coef_stride;\n"
"    int pad;\n"
"};\n"
"\n"
"#define VC2_TRANSFORM_HAAR (3)\n"
"#define VC2_TRANSFORM_HAAR_S (4)\n"
"#define VC2_TRANSFORM_5_3 (1)\n"
"\n"
"layout(push_constant, scalar) uniform ComputeInfo {\n"
"    int s;\n"
"    int diff_offset;\n"
"    int level;\n"
"    int wavelet_type;\n"
"    Plane planes[3];\n"
"    PlaneBuf src_buf[3];\n"
"    DwtCoef dst_buf[3];\n"
"};\n"
"\n"
"void main() {\n"
"    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
"    uint plane_idx = gl_GlobalInvocationID.z;\n"
"    ivec2 work_area = planes[plane_idx].dim;\n"
"    if (any(greaterThanEqual(coord, work_area))) {\n"
"        return;\n"
"    }\n"
"    int stride = planes[plane_idx].coef_stride;\n"
"    uint coef_idx = coord.y * stride + coord.x;\n"
"    uint8_t texel = src_buf[plane_idx].data[coef_idx];\n"
"    int result = int(texel - diff_offset);\n"
"    dst_buf[plane_idx].coef_buf[coef_idx] = result;\n"
"}\n"
;
