// Generated from libavcodec/vulkan/dwt_haar.comp
const char *ff_source_dwt_haar_comp =
"#extension GL_EXT_scalar_block_layout : require\n"
"\n"
"#define LOCAL_X 256\n"
"\n"
"layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;\n"
"\n"
"layout(scalar, buffer_reference, buffer_reference_align = 4) buffer DwtCoef {\n"
"    int coef_buf[];\n"
"};\n"
"\n"
"struct Plane {\n"
"    ivec2 dim;\n"
"    ivec2 dwt_dim;\n"
"};\n"
"\n"
"layout(push_constant, scalar) uniform ComputeInfo {\n"
"    int s;\n"
"    int plane_idx;\n"
"    int wavelet_depth;\n"
"    Plane planes[3];\n"
"    DwtCoef dst_buf[3];\n"
"    DwtCoef src_buf[3];\n"
"};\n"
"\n"
"shared int local_coef[LOCAL_X];\n"
"\n"
"void main() {\n"
"    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
"    ivec2 dwt_dim = planes[plane_idx].dwt_dim;\n"
"    if (any(greaterThanEqual(coord, dwt_dim))) {\n"
"        return;\n"
"    }\n"
"    int index = dwt_dim.x * coord.y + coord.x;\n"
"    int value = src_buf[plane_idx].coef_buf[index];\n"
"\n"
"    /* Perform Haar wavelet on the 16x16 local workgroup with shared memory */\n"
"    for (int i = 0; i < wavelet_depth; i++) {\n"
"        ivec2 mask = ivec2((1 << i) - 1);\n"
"        if (any(notEqual(coord & mask, ivec2(0)))) {\n"
"            break;\n"
"        }\n"
"        \n"
"        /* Offset between valid hor pixels for each level, +1, +2, +4 etc */\n"
"        int dist = (1 << i);\n"
"        \n"
"        local_coef[gl_LocalInvocationIndex] = value;\n"
"        barrier();\n"
"\n"
"        /* Horizontal haar wavelet */\n"
"        uint other_id = gl_LocalInvocationIndex ^ dist;\n"
"        int other = local_coef[other_id];\n"
"        int a = gl_LocalInvocationIndex < other_id ? value : other;\n"
"        int b = gl_LocalInvocationIndex < other_id ? other : value;\n"
"        int dst_b = (b - a) * (1 << s);\n"
"        int dst_a = a * (1 << s) + ((dst_b + 1) >> 1);\n"
"        value = gl_LocalInvocationIndex < other_id ? dst_a : dst_b;\n"
"\n"
"        /* Offset between valid ver pixels for each level, +1, +2, +4 etc */\n"
"        dist <<= 4;\n"
"\n"
"        local_coef[gl_LocalInvocationIndex] = value;\n"
"        barrier();\n"
"\n"
"        /* Vertical haar wavelet */\n"
"        other_id = gl_LocalInvocationIndex ^ dist;\n"
"        other = local_coef[other_id];\n"
"        a = gl_LocalInvocationIndex < other_id ? value : other;\n"
"        b = gl_LocalInvocationIndex < other_id ? other : value;\n"
"        dst_b = b - a;\n"
"        dst_a = a + ((dst_b + 1) >> 1);\n"
"        value = gl_LocalInvocationIndex < other_id ? dst_a : dst_b;\n"
"    }\n"
"\n"
"    /* Store value */\n"
"    src_buf[plane_idx].coef_buf[index] = value;\n"
"}\n";
